[project]
name = "connection-game"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pytest>=9.0.2",
    "scipy>=1.17.0",
    "snakeviz>=2.2.2",
]

[tool.pytest.ini_options]
pythonpath = "src"
